### ISSUE TITLE
Ctrl+C is not captured

### ISSUE THREAD

**Issue by evan2645** [phunt/zk-smoketest#6]
Ctrl+C is not captured and thus does not clean up after itself. After Ctrl+C on a latency test, the next test attempt resulted in:

```
Connected in 15 ms, handle is 0
Traceback (most recent call last):
  File "./zk-latencies.py", line 299, in <module>
    raise SmokeError("Node %s already exists!" % (options.root_znode))
__main__.SmokeError: 'Node /zk-latencies already exists!'
```

**Comment by phunt** [comment]
iirc that's why I added the --force option. There are lots of cases where it might crash out early, in addition to the case you mention.
